[package]
name = "service_core"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["rustls", "json"] }
strum = { version = "0.20.0", features = ["derive"] }
lambda_http = "0.3.0"
tonic = "0.6.1"
