[package]
name = "serde_ddb"
version = "0.1.0"
edition = "2021"


[dependencies]
aws-smithy-types = "0.39.0"
aws-sdk-dynamodb = "0.9.0"
serde = "1.0"
thiserror = "1.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
