#!/usr/bin/env python3

import subprocess
import json
import os

def main():
    if (len(os.sys.argv) != 2):
        print('expected service_name')
        os.sys.exit(-1)

    service_name = os.sys.argv[1]
    cmd = ['cargo', 'metadata', '--no-deps', '--format-version', '1']
    with subprocess.Popen(cmd, encoding='utf-8', stdout=subprocess.PIPE) as p:
        data_raw = p.stdout.read()
        meta = json.loads(data_raw)
        service_crate = None

        for package in meta['packages']:
            if package['metadata'] == None:
                continue

            if package['metadata']['service_name'] == service_name:
                service_crate = package
                break

        pkgid = service_crate['id'].split(' ', 1)[0]
        print(pkgid)


if __name__ == '__main__':
    main()
