blank_lines_upper_bound = 2
condense_wildcard_suffixes = true
edition = "2021"
format_macro_matchers = true
max_width = 120
imports_granularity = "Module"
reorder_imports = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
