apiVersion: apps/v1
kind: Deployment
metadata:
    name: refresh-token-cache
    labels:
        app: refresh-token-cache
spec:
    replicas: 1
    selector:
        matchLabels:
            app: refresh-token-cache
    template:
        metadata:
            labels:
                app: refresh-token-cache
        spec:
            containers:
                - name: refresh-token-cache
                  image: memcached:alpine
                  ports:
                      - containerPort: 11211
                        name: memcached
                  command:
                      - 'memcached'
                  args: ['-m', '64']
---
apiVersion: v1
kind: Service
metadata:
    name: refresh-token-cache
spec:
    selector:
        app: refresh-token-cache
    ports:
        - protocol: TCP
          port: 11211
          targetPort: memcached
