version: 2.1

jobs:
    prepare-builder:
        docker:
            - image: docker:20.10.17-git
              auth:
                  username: $DOCKERHUB_USERNAME
                  password: $DOCKERHUB_TOKEN
        environment:
            BUILDER_IMAGE_NAME: vicbarbu/uc-builder
        steps:
            - checkout
            - setup_remote_docker:
                  version: 20.10.14
                  docker_layer_caching: true
            - run:
                  name: Prepare builder image
                  command: |
                      docker build -t $BUILDER_IMAGE_NAME .
            - deploy:
                  name: Push to DockerHub
                  command: |
                      if [ "${CIRCLE_BRANCH}" == "mainline" ]; then
                          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
                          docker push $BUILDER_IMAGE_NAME
                      fi
    build-identity-service:
        docker:
            - image: vicbarbu/uc-builder:latest
              auth:
                  username: $DOCKERHUB_USERNAME
                  password: $DOCKERHUB_TOKEN
        environment:
            UC_IMAGE_TAG: vicbarbu/uc-identity-service
        steps:
            - checkout
            - setup_remote_docker:
                  version: 20.10.14
                  docker_layer_caching: true
            - run:
                  name: Build Backend
                  command: |
                      cargo make service build identity_service
            - deploy:
                  name: Push to DockerHub
                  command: |
                      if [ "${CIRCLE_BRANCH}" == "mainline" ]; then
                          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
                          docker push $UC_IMAGE_TAG
                      fi
    build-frontend:
        docker:
            - image: vicbarbu/uc-builder:latest
              auth:
                  username: $DOCKERHUB_USERNAME
                  password: $DOCKERHUB_TOKEN
        environment:
            UC_IMAGE_TAG: vicbarbu/uc-frontend
        steps:
            - checkout
            - setup_remote_docker:
                  version: 20.10.14
                  docker_layer_caching: true
            - run:
                  name: Build Backend
                  command: |
                      cargo make service build frontend
            - deploy:
                  name: Push to DockerHub
                  command: |
                      if [ "${CIRCLE_BRANCH}" == "mainline" ]; then
                          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
                          docker push $UC_IMAGE_TAG
                      fi

workflows:
    build-backend:
        jobs:
            - prepare-builder:
                  context:
                      - uc
            - build-identity-service:
                  requires:
                      - prepare-builder
                  context:
                      - uc
            - build-frontend:
                  requires:
                      - prepare-builder
                  context:
                      - uc

