[package]
name = "client"
version = "0.1.0"
edition = "2018"

[dependencies]
client_generator = { path = "../../../client_generator" }
service_client_runtime = { path = "../../../service_client_runtime" }
commons = { path = "../commons"}
